retriever:
  # Use Gemini embeddings for cloud deployment
  backend: gemini
  backend_configs:
    gemini:
      # API key from GOOGLE_API_KEY environment variable
      api_key: ""
      model_name: gemini-embedding-001
    openai:
      api_key: ""
      base_url: https://api.openai.com/v1
      model_name: text-embedding-3-small
    sentence_transformers:
      sentence_transformers_encode:
        encode_chunk_size: 256
        normalize_embeddings: false
        psg_prompt_name: document
        psg_task: null
        q_prompt_name: query
        q_task: null
      trust_remote_code: true
  batch_size: 16
  collection_name: default_collection
  corpus_path: data/corpus_example.jsonl
  embedding_path: embedding/embedding.npy
  gpu_ids: '0'
  # Use Milvus backend for cloud deployment
  index_backend: milvus
  index_backend_configs:
    faiss:
      index_chunk_size: 10000
      index_path: index/index.index
      index_use_gpu: false
    milvus:
      id_field_name: id
      id_max_length: 64
      index_chunk_size: 1000
      index_params:
        index_type: AUTOINDEX
        metric_type: IP
      metric_type: IP
      search_params:
        metric_type: IP
        params: {}
      text_field_name: contents
      text_max_length: 60000
      # Empty values will fall back to environment variables (MILVUS_URI, MILVUS_TOKEN)
      token: ""
      uri: ""
      vector_field_name: vector
  is_demo: false
  is_multimodal: false
  model_name_or_path: ""
  overwrite: false
